# Generated by Django 2.1 on 2019-12-14 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100, null=True)),
                ('picture', models.ImageField(upload_to='pictures/recruiter')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.AIRecruiter')),
            ],
            options={
                'db_table': 'recruiter_profile',
            },
        ),
    ]
